
import {
  createStyle,
} from 'src/styles';

export default createStyle({
  container: {
    backgroundColor: '#000000',
    flexDirection: 'column',
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    overflow: 'scroll',
  },
  filterBtn: {
    flex: 1,
  },
  photoContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadView: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  confirmBtn: {
    width: 300,
    height: 300,
    borderRadius: 300 / 2,
    borderWidth: 1,
    borderColor: '#ffffff',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  spotBtn: {
    borderWidth: 1,
    borderColor: '#ffffff',
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 10,
    width: '100%',
    textAlign: 'center',
  },
  subTitleText: {
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 22,
    color: '#ffffff',
    marginBottom: 10,
    width: '100%',
    textAlign: 'center',
  },
  text: {
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 15,
  },
  textFull: {
    backgroundColor: '#000000',
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Light',
    fontSize: 20,
    lineHeight: 20,
    borderBottomWidth: 0,
    borderBottomColor: '#fff',
    marginBottom: 10,
    padding: 10,
    width: '100%',
    margin: 5,
    height: 50,
    textAlign: 'left',
    elevation: 0,
  },
  courtText: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 18,
    flexWrap: 'wrap',
    lineHeight: 20,
    borderBottomWidth: 0,
    borderBottomColor: '#fff',
    marginBottom: 10,
    padding: 2,
    width: '100%',
    margin: 0,
    textAlign: 'left',
    elevation: 0,
  },
  textInput: {
    backgroundColor: '#000000',
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 20,
    lineHeight: 20,
    borderBottomWidth: 0,
    borderBottomColor: '#fff',
    marginBottom: 10,
    padding: 10,
    flexWrap: 'wrap',
    width: 150,
    margin: 5,
    height: 50,
    textAlign: 'left',
  },
  profileImage: {
    backgroundColor: '#ffffff',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
    width: 125,
    height: 125,
    borderColor: '#ffffff',
    borderWidth: 1,
  },
  profilePic: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  profile: {
    height: 30,
  },
  profileText: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 20,
  },
  searchInput: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 18,
    padding: 5,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    backgroundColor: '#333333',
  },
  photos: {
    margin: 5,
    width: 150,
    height: 150,
  },
  courtImageWrapper: {
    position: 'absolute',
    top: 75,
    left: 0,
    width: '100%',
    height: 190,
    borderBottomWidth: 2,
    borderColor: '#222222',
  },
  courtImage: {
    flex: 1,
    resizeMode: 'cover',
    width: '100%',
    height: '100%',
    opacity: 0.5,

  },
  modal: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeader: {
    backgroundColor: '#000000',
    top: 0,
    width: '100%',
    height: 50,
  },
  modalWrapper: {
    flex: 1,
    width: '100%',
    padding: 20,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  close: {
    height: 50,
    width: 100,
    right: 0,
  },
  closeText: {
    color: '#ffffff',
    textAlign: 'center',
    fontSize: 22,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'BarlowCondensed-Bold',
  },
  squadButtons: {
    height: 70,
    marginBottom: 15,
  },
  addBtn: {
    backgroundColor: '#478cba',
    height: 70,
    width: '100%',
    bottom: 0,
  },
  addBtnText: {
    textAlign: 'center',
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 20,
  },
  runTab: {
    textAlign: 'center',
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 16,
  },
  listText: {
    textAlign: 'center',
    color: '#000000',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 16,
  },
  courtBtnText: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Medium',
  },
  addImageBtn: {
    position: 'absolute',
    right: 10,
    backgroundColor: '#478cba',
    width: 100,
    height: '100%',
    zIndex: 9,
  },
  uploadButton: {
    backgroundColor: '#478cba',
    borderWidth: 0,
    borderColor: '#fff',
    marginBottom: 0,
    padding: 15,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    zIndex: 9,
  },
  viewList: {
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
