import { StyleSheet } from 'react-native';

const cellStyle = StyleSheet.create({
  listContainer: {
    flex: 1,
    backgroundColor: '#EBEBEB',
    borderRadius: 10,
    margin: 10,
    overflow: 'hidden',
  },
  courtDetail: {
    flexDirection: 'row',
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
    width: '80%',
  },
  memberCheckin: {
    flexDirection: 'row',
  },
  imageContainer: {
    height: 100,
    width: 100,
    borderRadius: 50,
    overflow: 'hidden',
    borderColor: '#ffffff',
    borderWidth: 5,
  },
  courtImageContainer: {
    height: 100,
    width: 100,
    borderRadius: 50,
    overflow: 'hidden',
    borderColor: '#498BBA',
    borderWidth: 5,
  },
  userColumn: {
    padding: 10,
    backgroundColor: '#4A8ABA',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: '#ffffff',
    borderRightWidth: 2,
  },
  courtColumn: {
    padding: 10,
    width: 155,
    backgroundColor: '#EDEDED',
    alignItems: 'center',
    justifyContent: 'center',
    borderRightColor: '#707070',
    borderRightWidth: 1,
  },
  detailColumn: {
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  statColumn: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  selectBtn: {
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    padding: 0,
  },
  profileImageWrapper: {
    width: 100,
    height: 100,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  profileImage: {
    width: 120,
    height: 120,
  },
  courtGames: {
    flexDirection: 'row',
  },
  gameCount: {
    fontFamily: 'BarlowCondensed-Bold',
    color: '#3C3C3C',
    fontSize: 42,
  },
  gameTextContainer: {
    padding: 10,
  },
  gameText: {
    fontFamily: 'BarlowCondensed-Bold',
    color: '#3C3C3C',
  },
  cellText: {
    fontFamily: 'BarlowCondensed-Bold',
    color: '#ffffff',
  },
  headerText: {
    color: 'white',
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 24,
    flexShrink: 1,
  },
  subText: {
    color: 'white',
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 14,
  },
  jamesRatingContainer: {
    backgroundColor: '#ffffff',
    margin: 10,
    height: 100,
    width: 100,
    borderRadius: 50,
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: 'BarlowCondensed-Medium',
    borderColor: '#2CC9C3',
    borderWidth: 5,
  },
  detail: {
    flex: 1,
    width: '100%',
    padding: 10,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  rating: {
    flex: 1.25,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stats: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopColor: '#707070',
    borderTopWidth: 1,
    margin: 0,
    padding: 0,
  },
  edits: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderTopColor: '#707070',
    borderTopWidth: 1,
    margin: 0,
    padding: 0,
  },
  editButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statScore: {
    margin: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  score: {
    color: '#3C3C3C',
    fontFamily: 'BarlowCondensed-Bold',
  },
  title: {
    color: '#3C3C3C',
    fontFamily: 'BarlowCondensed-Medium',
  },
  iconActive: {
    opacity: 1,
    color: '#478cba',
    fontSize: 40,
    alignSelf: 'center',
    marginRight: 0,
    marginLeft: 0,
  },
  iconInActive: {
    opacity: 1,
    color: 'white',
    fontSize: 40,
    alignSelf: 'center',
    marginRight: 0,
    marginLeft: 0,
  },
});

export default cellStyle;
