// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_cognito_identity_pool_id: 'us-east-1:d1a51fe5-1919-46e7-81d1-a45519b793d3',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_b2v4W4o2b',
  aws_user_pools_web_client_id: 'rgkipisk9lqk2d9i144u3712l',
  aws_user_files_s3_bucket: 'james-james',
  aws_user_files_s3_bucket_region: 'us-east-1',
};

export default awsmobile;
