
import {
  createStyle,
} from 'src/styles';

export default createStyle({
  modalHeader: {
    backgroundColor: '#000000',
    top: 0,
    width: '100%',
    height: 50,
    marginBottom: 10,
  },
  modalWrapper: {
    flex: 1,
    width: '100%',
    padding: 20,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  close: {
    height: 50,
    width: 100,
    right: 0,
  },
  closeText: {
    color: '#ffffff',
    textAlign: 'center',
    fontSize: 22,
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    fontFamily: 'BarlowCondensed-Bold',
  },
  squadButtons: {
    height: 70,
    marginBottom: 15,
  },
  confirmBtn: {
    width: 300,
    height: 300,
    borderRadius: 300 / 2,
    borderWidth: 1,
    borderColor: '#ffffff',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  spotBtn: {
    borderWidth: 1,
    borderColor: '#ffffff',
    width: 100,
    height: 100,
    borderRadius: 100 / 2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  titleText: {
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 18,
    color: '#ffffff',
    marginBottom: 10,
    width: '100%',
    textAlign: 'center',
  },
  subTitleText: {
    fontFamily: 'BarlowCondensed-Medium',
    fontSize: 22,
    color: '#ffffff',
    marginBottom: 10,
    width: '100%',
    textAlign: 'center',
  },
  gameDate: {
    fontFamily: 'BarlowCondensed-Light',
    color: '#ffffff',
    fontSize: 18,
    textAlign: 'center',
  },
  gameScore: {
    fontFamily: 'BarlowCondensed-Bold',
    color: '#ffffff',
    fontSize: 26,
    textAlign: 'center',
  },
  gameTitle: {
    fontFamily: 'BarlowCondensed-Bold',
    color: '#ffffff',
    fontSize: 18,
    textAlign: 'center',
  },
  container: {
    backgroundColor: '#000000',
  },
  boardItem: {
    backgroundColor: '#000000',
    marginBottom: 10,
    padding: 10,
    width: '80%',
    marginLeft: 'auto',
    marginRight: 'auto',
    borderRadius: 5,
  },
  message: {
    backgroundColor: '#000000',
    fontFamily: 'BarlowCondensed-Bold',
    color: '#ffffff',
    padding: 5,
    fontSize: 14,
    textAlign: 'center',
    width: '100%',
  },
  filterBtn: {
    flex: 1,
  },
  runLocation: {
    position: 'absolute',
    width: '100%',
    left: 10,
    bottom: 10,
  },
  runLocationText: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Light',
    fontSize: 18,
  },
  startBtn: {
    width: '100%',
    height: '100%',
    backgroundColor: '#044571',
    flexDirection: 'row',
  },
  startBtnText: {
    flex: 1,
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 15,
    color: '#ffffff',
    textAlign: 'center',
    flexWrap: 'wrap',
  },
  text: {
    fontFamily: 'BarlowCondensed-Light',
    fontSize: 18,
    color: '#ffffff',
    lineHeight: 24,
  },
});
