
export default {
  loginBox: {
    position: 'relative',
    width: '90%',
    height: 450,
    padding: 5,
    backgroundColor: 'rgba(60,60,60,.8)',
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
  },
  header: {
    color: '#ffffff',
    fontFamily: 'BarlowCondensed-Bold',
    fontSize: 16,
    paddingTop: 10,
    paddingBottom: 30,
  },
  logo: {
    width: 80,
    height: 80,
    margin: 'auto',
    justifyContent: 'center',
  },
  registerBox: {
    // position: 'relative',
    // width: '100%',
    padding: 5,
    backgroundColor: 'rgba(60,60,60,.8)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  container: {
    backgroundColor: '#000000',
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeader: {
    alignSelf: 'flex-start',
  },
  nextButton: {
    marginBottom: 100,
  },
  close: {
    marginTop: 60,
    alignSelf: 'flex-start',
  },
  closeText: {
    width: '100%',
    color: '#FFFFFF',
    textAlign: 'left',
    fontSize: 22,
    flex: 0.1,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    fontFamily: 'ProximaNova-Bold',
  },
  resendBtn: {
    width: '80%',
    height: 50,
    textAlign: 'center',
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderBottomWidth: 0,
    borderBottomColor: '#ffffff',
  },
  textInput: {
    color: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#fff',
    marginBottom: '5%',
    padding: '5%',
    width: '80%',
    height: 60,
    textAlign: 'center',
    elevation: 0,
  },
  loginButton: {
    backgroundColor: '#478cba',
    borderWidth: 0,
    borderColor: '#fff',
    marginBottom: 0,
    padding: 15,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
};
