
export default {
  APP_UPDATE: 'AppUpdate',
  APP_ERROR: 'AppError',
  LOGIN: 'Login',
  REGISTER: 'Register',
  REGISTER_DETAILS: 'RegisterDetails',
  GAME_LISTING: 'GameListing',
  RUN_LISTING: 'RunListing',
  SINGLE_RUN: 'SingleRun',
  EXHIBITION_GAME: 'ExhibitionGame',
  TEAM_BOARD: 'TeamBoard',
  RUN: 'Run',
  PROFILE: 'Profile',
  BALLERS: 'Ballers',
  BALLER_PROFILE: 'BallerProfile',
  MANAGEMENT: 'Management',
  NEW_MEMBER: 'NewMember',
  EDIT_BALLER: 'EditBaller',
  NEW_COURT: 'NewCourt',
  EDIT_COURT: 'EditCourt',
  ADD_GAME: 'AddGame',
  ADD_GAME_LIST: 'AddGameList',
  ADD_GAME_TEAMS: 'AddGameTeams',
  ADD_GAME_FINAL: 'AddGameFinal',
  ADD_GAME_NO_STAFF: 'AddGameNoStaff',
  COURTS: 'COURTS',
  BALLER: 'Baller',
  COURT: 'Court',
  TEAM: 'Team',
  LEAGUE: 'League',
  RESERVE_SPOT: 'ReserveSpot',
  RESERVE_SPOT_MANAGER: 'ReserveSpotManager',
};
